<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="home.php">
        <img src="https://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png" width="30" height="30" class="d-inline-block align-top" alt="">
        Tyrolium Panel
    </a>

    <?php if (!empty($_SESSION['userIdLog'])){ ?>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item <?php if ($page == 1){ echo "active"; } ?> ">
                    <a class="nav-link" href="home.php">Accueil</a>
                </li>
                <li class="nav-item <?php if ($page == 3){ echo "active"; } ?> ">
                    <a class="nav-link" href="user.php">Membre</a>
                </li>
                <li class="nav-item <?php if ($page == 6){ echo "active"; } ?> ">
                    <a class="nav-link" href="contact.php">Contact</a>
                </li>
            </ul>
            <form class="form-inline" method="POST" action="?logout=true">
                <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Déconnexion</button>
            </form>
        </div>
    <?php } ?>
</nav>